
development:
  secret_key_base: a%3002irjfnb)83r^0)($nxug#)hdiuyT53V*#nnx)*!!666

test:
  secret_key_base: a%3002irjfnb)83r^0

production:
  secret_key_base: ENV['SECRET_KEY_BASE']
  GMAIL_USERNAME: ENV['GMAIL_USERNAME']
  GMAIL_PASSWORD: ENV['GMAIL_PASSWORD']
