AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'ATT', size: 32, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'ATT', size: 256, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'ATT', size: 128, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'Sprint', size: 32, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'Sprint', size: 256, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'Sprint', size: 128, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'T-Mobile', size: 32, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'T-Mobile', size: 256, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'T-Mobile', size: 128, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'Verizon', size: 32, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'Verizon', size: 256, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'Verizon', size: 128, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'Other', size: 32, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'Other', size: 256, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 9.7-inch', network: 'Other', size: 128, image: '../assets/images/ipad-pro-9-7.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'ATT', size: 32, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'ATT', size: 256, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'ATT', size: 128, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'Sprint', size: 32, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'Sprint', size: 256, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'Sprint', size: 128, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'T-Mobile', size: 32, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'T-Mobile', size: 256, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'T-Mobile', size: 128, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'Verizon', size: 32, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'Verizon', size: 256, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'Verizon', size: 128, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'Other', size: 32, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'Other', size: 256, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Pro 12.9-inch', network: 'Other', size: 128, image: 'ipad-pro.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'ATT', size: 16, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'ATT', size: 64, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'ATT', size: 128, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'Sprint', size: 16, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'Sprint', size: 64, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'Sprint', size: 128, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'T-Mobile', size: 16, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'T-Mobile', size: 64, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'T-Mobile', size: 128, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'Verizon', size: 16, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'Verizon', size: 64, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'Verizon', size: 128, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'Other', size: 16, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'Other', size: 64, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air 2', network: 'Other', size: 128, image: 'ipad-air2.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'ATT', size: 16, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'ATT', size: 32, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'ATT', size: 64, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'ATT', size: 128, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Sprint', size: 16, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Sprint', size: 32, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Sprint', size: 64, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Sprint', size: 128, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'T-Mobile', size: 16, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'T-Mobile', size: 32, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'T-Mobile', size: 64, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'T-Mobile', size: 128, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Verizon', size: 16, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Verizon', size: 32, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Verizon', size: 64, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Verizon', size: 128, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Other', size: 16, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Other', size: 32, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Other', size: 64, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'Air', network: 'Other', size: 128, image: 'ipad-air.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'ATT', size: 16, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'ATT', size: 64, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'ATT', size: 128, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'Sprint', size: 16, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'Sprint', size: 64, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'Sprint', size: 128, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'T-Mobile', size: 16, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'T-Mobile', size: 64, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'T-Mobile', size: 128, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'Verizon', size: 16, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'Verizon', size: 64, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'Verizon', size: 128, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'Other', size: 16, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'Other', size: 64, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 4', network: 'Other', size: 128, image: 'ipad-mini4.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'ATT', size: 16, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'ATT', size: 64, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'ATT', size: 128, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'Sprint', size: 16, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'Sprint', size: 64, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'Sprint', size: 128, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'T-Mobile', size: 16, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'T-Mobile', size: 64, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'T-Mobile', size: 128, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'Verizon', size: 16, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'Verizon', size: 64, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'Verizon', size: 128, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'Other', size: 16, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'Other', size: 64, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 3', network: 'Other', size: 128, image: 'ipad-mini3.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'ATT', size: 16, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'ATT', size: 32, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'ATT', size: 64, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'ATT', size: 128, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Sprint', size: 16, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Sprint', size: 32, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Sprint', size: 64, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Sprint', size: 128, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'T-Mobile', size: 16, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'T-Mobile', size: 32, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'T-Mobile', size: 64, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'T-Mobile', size: 128, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Verizon', size: 16, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Verizon', size: 32, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Verizon', size: 64, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Verizon', size: 128, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Other', size: 16, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Other', size: 32, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Other', size: 64, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini 2', network: 'Other', size: 128, image: 'ipad-mini2.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'ATT', size: 16, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'ATT', size: 64, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'ATT', size: 32, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'Sprint', size: 16, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'Sprint', size: 64, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'Sprint', size: 32, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'T-Mobile', size: 16, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'T-Mobile', size: 64, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'T-Mobile', size: 32, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'Verizon', size: 16, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'Verizon', size: 64, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'Verizon', size: 32, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'Other', size: 16, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'Other', size: 64, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: 'mini', network: 'Other', size: 32, image: 'ipad-mini.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'ATT', size: 16, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'ATT', size: 32, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'ATT', size: 64, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'ATT', size: 128, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Sprint', size: 16, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Sprint', size: 32, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Sprint', size: 64, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Sprint', size: 128, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'T-Mobile', size: 16, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'T-Mobile', size: 32, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'T-Mobile', size: 64, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'T-Mobile', size: 128, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Verizon', size: 16, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Verizon', size: 32, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Verizon', size: 64, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Verizon', size: 128, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Other', size: 16, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Other', size: 32, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Other', size: 64, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '4th generation', network: 'Other', size: 128, image: 'ipad-4gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'ATT', size: 16, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'ATT', size: 64, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'ATT', size: 32, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'Sprint', size: 16, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'Sprint', size: 64, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'Sprint', size: 32, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'T-Mobile', size: 16, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'T-Mobile', size: 64, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'T-Mobile', size: 32, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'Verizon', size: 16, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'Verizon', size: 64, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'Verizon', size: 32, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'Other', size: 16, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'Other', size: 64, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '3rd generation', network: 'Other', size: 32, image: 'ipad-3gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'ATT', size: 16, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'ATT', size: 64, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'ATT', size: 32, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'Sprint', size: 16, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'Sprint', size: 64, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'Sprint', size: 32, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'T-Mobile', size: 16, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'T-Mobile', size: 64, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'T-Mobile', size: 32, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'Verizon', size: 16, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'Verizon', size: 64, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'Verizon', size: 32, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'Other', size: 16, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'Other', size: 64, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: '2nd generation', network: 'Other', size: 32, image: 'ipad-2gen.jpg')
Device.create(name: 'iPad', model: 'original', network: 'ATT', size: 16, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'ATT', size: 64, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'ATT', size: 32, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'Sprint', size: 16, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'Sprint', size: 64, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'Sprint', size: 32, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'T-Mobile', size: 16, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'T-Mobile', size: 64, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'T-Mobile', size: 32, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'Verizon', size: 16, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'Verizon', size: 64, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'Verizon', size: 32, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'Other', size: 16, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'Other', size: 64, image: 'ipad.jpg')
Device.create(name: 'iPad', model: 'original', network: 'Other', size: 32, image: 'ipad.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'ATT', size: 16, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'ATT', size: 64, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'ATT', size: 128, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'Sprint', size: 16, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'Sprint', size: 64, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'Sprint', size: 128, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'T-Mobile', size: 16, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'T-Mobile', size: 64, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'T-Mobile', size: 128, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'Verizon', size: 16, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'Verizon', size: 64, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'Verizon', size: 128, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'Other', size: 16, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'Other', size: 64, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s Plus', network: 'Other', size: 128, image: 'iphone-6splus.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'ATT', size: 16, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'ATT', size: 64, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'ATT', size: 128, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'Sprint', size: 16, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'Sprint', size: 64, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'Sprint', size: 128, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'T-Mobile', size: 16, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'T-Mobile', size: 64, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'T-Mobile', size: 128, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'Verizon', size: 16, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'Verizon', size: 64, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'Verizon', size: 128, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'Other', size: 16, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'Other', size: 64, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6s', network: 'Other', size: 128, image: 'iphone-6s.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'ATT', size: 16, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'ATT', size: 64, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'ATT', size: 128, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'Sprint', size: 16, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'Sprint', size: 64, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'Sprint', size: 128, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'T-Mobile', size: 16, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'T-Mobile', size: 64, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'T-Mobile', size: 128, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'Verizon', size: 16, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'Verizon', size: 64, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'Verizon', size: 128, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'Other', size: 16, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'Other', size: 64, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6 Plus', network: 'Other', size: 128, image: 'iphone6plus.jpg')
Device.create(name: 'iPhone', model: '6', network: 'ATT', size: 16, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'ATT', size: 64, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'ATT', size: 128, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'Sprint', size: 16, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'Sprint', size: 64, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'Sprint', size: 128, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'T-Mobile', size: 16, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'T-Mobile', size: 64, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'T-Mobile', size: 128, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'Verizon', size: 16, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'Verizon', size: 64, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'Verizon', size: 128, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'Other', size: 16, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'Other', size: 64, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: '6', network: 'Other', size: 128, image: 'iphone6.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'ATT', size: 16, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'ATT', size: 64, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'Sprint', size: 16, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'Sprint', size: 64, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'T-Mobile', size: 16, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'T-Mobile', size: 64, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'Verizon', size: 16, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'Verizon', size: 64, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'Other', size: 16, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: 'SE', network: 'Other', size: 64, image: 'iphone-se.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'ATT', size: 16, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'ATT', size: 64, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'ATT', size: 32, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'Sprint', size: 16, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'Sprint', size: 64, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'Sprint', size: 32, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'T-Mobile', size: 16, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'T-Mobile', size: 64, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'T-Mobile', size: 32, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'Verizon', size: 16, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'Verizon', size: 64, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'Verizon', size: 32, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'Other', size: 16, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'Other', size: 64, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5s', network: 'Other', size: 32, image: 'iphone5s.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'ATT', size: 16, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'ATT', size: 8, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'ATT', size: 32, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'Sprint', size: 16, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'Sprint', size: 8, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'Sprint', size: 32, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'T-Mobile', size: 16, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'T-Mobile', size: 8, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'T-Mobile', size: 32, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'Verizon', size: 16, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'Verizon', size: 8, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'Verizon', size: 32, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'Other', size: 16, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'Other', size: 8, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5c', network: 'Other', size: 32, image: 'iphone5c.jpg')
Device.create(name: 'iPhone', model: '5', network: 'ATT', size: 16, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'ATT', size: 64, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'ATT', size: 32, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'Sprint', size: 16, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'Sprint', size: 64, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'Sprint', size: 32, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'T-Mobile', size: 16, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'T-Mobile', size: 64, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'T-Mobile', size: 32, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'Verizon', size: 16, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'Verizon', size: 64, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'Verizon', size: 32, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'Other', size: 16, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'Other', size: 64, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '5', network: 'Other', size: 32, image: 'iphone5.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'ATT', size: 16, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'ATT', size: 64, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'ATT', size: 32, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'ATT', size: 8, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Sprint', size: 16, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Sprint', size: 64, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Sprint', size: 32, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Sprint', size: 8, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'T-Mobile', size: 16, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'T-Mobile', size: 64, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'T-Mobile', size: 32, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'T-Mobile', size: 8, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Verizon', size: 16, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Verizon', size: 64, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Verizon', size: 32, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Verizon', size: 8, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Other', size: 16, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Other', size: 64, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Other', size: 32, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4s', network: 'Other', size: 8, image: 'iphone4s.jpg')
Device.create(name: 'iPhone', model: '4', network: 'ATT', size: 16, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'ATT', size: 32, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'ATT', size: 8, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'Sprint', size: 16, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'Sprint', size: 32, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'Sprint', size: 8, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'T-Mobile', size: 16, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'T-Mobile', size: 32, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'T-Mobile', size: 8, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'Verizon', size: 16, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'Verizon', size: 32, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'Verizon', size: 8, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'Other', size: 16, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'Other', size: 32, image: 'iphone4.jpg')
Device.create(name: 'iPhone', model: '4', network: 'Other', size: 8, image: 'iphone4.jpg')
Device.create(name: 'Galaxy', model: 'S7', network: 'ATT', size: 32, image: 'galaxy-s7.png')
Device.create(name: 'Galaxy', model: 'S7', network: 'Sprint', size: 32, image: 'galaxy-s7.png')
Device.create(name: 'Galaxy', model: 'S7', network: 'T-Mobile', size: 32, image: 'galaxy-s7.png')
Device.create(name: 'Galaxy', model: 'S7', network: 'Verizon', size: 32, image: 'galaxy-s7.png')
Device.create(name: 'Galaxy', model: 'S7', network: 'Other', size: 32, image: 'galaxy-s7.png')
Device.create(name: 'Galaxy', model: 'S7 edge', network: 'ATT', size: 32, image: 'galaxy-s7edge.jpg')
Device.create(name: 'Galaxy', model: 'S7 edge', network: 'Sprint', size: 32, image: 'galaxy-s7edge.jpg')
Device.create(name: 'Galaxy', model: 'S7 edge', network: 'T-Mobile', size: 32, image: 'galaxy-s7edge.jpg')
Device.create(name: 'Galaxy', model: 'S7 edge', network: 'Verizon', size: 32, image: 'galaxy-s7edge.jpg')
Device.create(name: 'Galaxy', model: 'S7 edge', network: 'Other', size: 32, image: 'galaxy-s7edge.jpg')
Device.create(name: 'Galaxy', model: 'S6', network: 'ATT', size: 32, image: 'galaxy-s6.png')
Device.create(name: 'Galaxy', model: 'S6', network: 'Sprint', size: 32, image: 'galaxy-s6.png')
Device.create(name: 'Galaxy', model: 'S6', network: 'T-Mobile', size: 32, image: 'galaxy-s6.png')
Device.create(name: 'Galaxy', model: 'S6', network: 'Verizon', size: 32, image: 'galaxy-s6.png')
Device.create(name: 'Galaxy', model: 'S6', network: 'Other', size: 32, image: 'galaxy-s6.png')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'ATT', size: 32, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'Sprint', size: 32, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'T-Mobile', size: 32, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'Verizon', size: 32, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'Other', size: 32, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'ATT', size: 128, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'Sprint', size: 128, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'T-Mobile', size: 128, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'Verizon', size: 128, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S6 edge', network: 'Other', size: 128, image: 'galaxy-6sedge.jpg')
Device.create(name: 'Galaxy', model: 'S5', network: 'ATT', size: 32, image: 'galaxy-s5.jpg')
Device.create(name: 'Galaxy', model: 'S5', network: 'Sprint', size: 32, image: 'galaxy-s5.jpg')
Device.create(name: 'Galaxy', model: 'S5', network: 'T-Mobile', size: 32, image: 'galaxy-s5.jpg')
Device.create(name: 'Galaxy', model: 'S5', network: 'Verizon', size: 32, image: 'galaxy-s5.jpg')
Device.create(name: 'Galaxy', model: 'S5', network: 'Other', size: 32, image: 'galaxy-s5.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'ATT', size: 32, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'Sprint', size: 32, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'T-Mobile', size: 32, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'Verizon', size: 32, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'Other', size: 32, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'ATT', size: 16, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'Sprint', size: 16, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'T-Mobile', size: 16, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'Verizon', size: 16, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'S4', network: 'Other', size: 16, image: 'galaxy-s4.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'ATT', size: 32, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'Sprint', size: 32, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'T-Mobile', size: 32, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'Verizon', size: 32, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'Other', size: 32, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'ATT', size: 64, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'Sprint', size: 64, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'T-Mobile', size: 64, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'Verizon', size: 64, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note 5', network: 'Other', size: 64, image: 'galaxy-note5.jpg')
Device.create(name: 'Galaxy', model: 'Note edge', network: 'ATT', size: 32, image: 'galaxy-note-edge.jpg')
Device.create(name: 'Galaxy', model: 'Note edge', network: 'Sprint', size: 32, image: 'galaxy-note-edge.jpg')
Device.create(name: 'Galaxy', model: 'Note edge', network: 'T-Mobile', size: 32, image: 'galaxy-note-edge.jpg')
Device.create(name: 'Galaxy', model: 'Note edge', network: 'Verizon', size: 32, image: 'galaxy-note-edge.jpg')
Device.create(name: 'Galaxy', model: 'Note edge', network: 'Other', size: 32, image: 'galaxy-note-edge.jpg')
Device.create(name: 'Galaxy', model: 'Note 4', network: 'ATT', size: 32, image: 'galaxy-note4.jpg')
Device.create(name: 'Galaxy', model: 'Note 4', network: 'Sprint', size: 32, image: 'galaxy-note4.jpg')
Device.create(name: 'Galaxy', model: 'Note 4', network: 'T-Mobile', size: 32, image: 'galaxy-note4.jpg')
Device.create(name: 'Galaxy', model: 'Note 4', network: 'Verizon', size: 32, image: 'galaxy-note4.jpg')
Device.create(name: 'Galaxy', model: 'Note 4', network: 'Other', size: 32, image: 'galaxy-note4.jpg')
Device.create(name: 'Galaxy', model: 'Note 3', network: 'ATT', size: 32, image: 'galaxy-note3.jpg')
Device.create(name: 'Galaxy', model: 'Note 3', network: 'Sprint', size: 32, image: 'galaxy-note3.jpg')
Device.create(name: 'Galaxy', model: 'Note 3', network: 'T-Mobile', size: 32, image: 'galaxy-note3.jpg')
Device.create(name: 'Galaxy', model: 'Note 3', network: 'Verizon', size: 32, image: 'galaxy-note3.jpg')
Device.create(name: 'Galaxy', model: 'Note 3', network: 'Other', size: 32, image: 'galaxy-note3.jpg')

Offering.create(device_id: '', condition: 'without power', price: '$5')
Offering.create(device_id: '', condition: 'broken', price: '$25')
Offering.create(device_id: '', condition: 'normal', price: '$100')
