Brand.create(brand_name: 'Apple')
Brand.create(brand_name: 'Samsung')

Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'ATT', network_image: 'att-svg.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Other', network_image: 'wireless-tower-svg.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-pro.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'ATT', network_image: 'att-svg.png', size: 256, image: 'ipad-pro.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-pro.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-pro.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 256, image: 'ipad-pro.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-pro.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-pro.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 256, image: 'ipad-pro.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-pro.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-pro.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 256, image: 'ipad-pro.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-pro.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'ipad-pro.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Other', network_image: 'wireless-tower-svg.png', size: 256, image: 'ipad-pro.jpg', price_cents: 36000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'ipad-pro.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-air2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-air2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-air2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-air2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-air2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-air2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-air2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-air2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-air2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-air2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-air2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-air2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad-air2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad-air2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'ipad-air2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-air.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-air.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-air.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-air.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-air.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-air.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-air.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-air.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-air.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-air.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-air.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-air.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-air.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-air.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-air.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-air.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad-air.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'ipad-air.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad-air.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'ipad-air.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-mini.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-mini.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-mini.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-mini.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-mini.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-mini.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-mini.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-mini.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-mini.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-mini.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-mini.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-mini.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad-mini.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad-mini.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'ipad-mini.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'ipad.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'ipad.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'ipad.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 32000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'ATT', network_image: 'att-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Sprint', network_image: 'sprint-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Verizon', network_image: 'verizon-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Other', network_image: 'wireless-tower-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone4s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone4s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'iphone4s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'ATT', network_image: 'att-svg.png', size: 8, image: 'iphone4s.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone4s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone4s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'iphone4s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Sprint', network_image: 'sprint-svg.png', size: 8, image: 'iphone4s.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone4s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone4s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'iphone4s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 8, image: 'iphone4s.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone4s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone4s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'iphone4s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Verizon', network_image: 'verizon-svg.png', size: 8, image: 'iphone4s.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone4s.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone4s.jpg', price_cents: 28000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'iphone4s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 8, image: 'iphone4s.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'iphone4.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'ATT', network_image: 'att-svg.png', size: 8, image: 'iphone4.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'iphone4.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'Sprint', network_image: 'sprint-svg.png', size: 8, image: 'iphone4.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'iphone4.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 8, image: 'iphone4.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'iphone4.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'Verizon', network_image: 'verizon-svg.png', size: 8, image: 'iphone4.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'iphone4.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 8, image: 'iphone4.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'galaxy-6sedge.jpg', price_cents: 32000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'galaxy-6sedge.jpg', price_cents: 32000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'galaxy-6sedge.jpg', price_cents: 32000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'galaxy-6sedge.jpg', price_cents: 32000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'galaxy-6sedge.jpg', price_cents: 32000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'galaxy-s4.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'galaxy-s4.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'galaxy-s4.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'galaxy-s4.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'galaxy-s4.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'galaxy-note5.jpg', price_cents: 28000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'galaxy-note5.jpg', price_cents: 28000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'galaxy-note5.jpg', price_cents: 28000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'galaxy-note5.jpg', price_cents: 28000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'galaxy-note5.jpg', price_cents: 28000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 24000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 24000, brand_id: 2)

AdminUser.create!(email: 'psswf1172@yahoo.com', password: 'password', password_confirmation: 'password')

Quote.create(name: "Jen Abella", phone: "7324858930", device: 'iPhone', model: '6', network: 'ATT', size: 16, condition: 'normal', price_cents: 20000)