Brand.create(brand_name: 'Apple')
Brand.create(brand_name: 'Samsung')

Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 27500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'ATT', network_image: 'att-svg.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 27500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 27500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 27500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 27500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 32500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'Unlocked', network_image: 'unlocked.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'WIFI ONLY', network_image: 'wifi.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 25000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'WIFI ONLY', network_image: 'wifi.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 30000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 9.7-inch', network: 'WIFI ONLY', network_image: 'wifi.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 35000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-pro.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-pro.jpg', price_cents: 40000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'ATT', network_image: 'att-svg.png', size: 256, image: 'ipad-pro.jpg', price_cents: 45000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-pro.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-pro.jpg', price_cents: 40000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Sprint', network_image: 'sprint-svg.png', size: 256, image: 'ipad-pro.jpg', price_cents: 45000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-pro.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-pro.jpg', price_cents: 40000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 256, image: 'ipad-pro.jpg', price_cents: 45000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-pro.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-pro.jpg', price_cents: 40000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Verizon', network_image: 'verizon-svg.png', size: 256, image: 'ipad-pro.jpg', price_cents: 45000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'ipad-pro.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'ipad-pro.jpg', price_cents: 40000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'Unlocked', network_image: 'unlocked.png', size: 256, image: 'ipad-pro.jpg', price_cents: 45000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'WIFI ONLY', network_image: 'wifi.png', size: 32, image: 'ipad-pro-9-7.jpg', price_cents: 37500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'WIFI ONLY', network_image: 'wifi.png', size: 128, image: 'ipad-pro-9-7.jpg', price_cents: 40000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Pro 12.9-inch', network: 'WIFI ONLY', network_image: 'wifi.png', size: 256, image: 'ipad-pro-9-7.jpg', price_cents: 40000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-air2.jpg', price_cents: 15500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-air2.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-air2.jpg', price_cents: 18000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-air2.jpg', price_cents: 15500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-air2.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-air2.jpg', price_cents: 18000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-air2.jpg', price_cents: 15500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-air2.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-air2.jpg', price_cents: 18000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-air2.jpg', price_cents: 15500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-air2.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-air2.jpg', price_cents: 18000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad-air2.jpg', price_cents: 15500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad-air2.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'ipad-air2.jpg', price_cents: 18000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad-air2.jpg', price_cents: 14500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad-air2.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air 2', network: 'WIFI ONLY', network_image: 'wifi.png', size: 128, image: 'ipad-air2.jpg', price_cents: 17000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-air.jpg', price_cents: 10500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-air.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-air.jpg', price_cents: 11500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-air.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-air.jpg', price_cents: 10500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-air.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-air.jpg', price_cents: 11500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-air.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-air.jpg', price_cents: 10500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-air.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-air.jpg', price_cents: 11500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-air.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-air.jpg', price_cents: 10500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-air.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-air.jpg', price_cents: 11500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-air.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad-air.jpg', price_cents: 10500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'ipad-air.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad-air.jpg', price_cents: 11500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'ipad-air.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad-air.jpg', price_cents: 9500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'WIFI ONLY', network_image: 'wifi.png', size: 32, image: 'ipad-air.jpg', price_cents: 9500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad-air.jpg', price_cents: 10500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'Air', network: 'WIFI ONLY', network_image: 'wifi.png', size: 128, image: 'ipad-air.jpg', price_cents: 11500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 18500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 18500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 18500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 18500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 18500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad-mini4.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad-mini4.jpg', price_cents: 18500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 4', network: 'WIFI ONLY', network_image: 'wifi.png', size: 128, image: 'ipad-mini4.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad-mini3.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad-mini3.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 3', network: 'WIFI ONLY', network_image: 'wifi.png', size: 128, image: 'ipad-mini3.jpg', price_cents: 12500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 7500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 7500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 7500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 7500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 7500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad-mini2.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'WIFI ONLY', network_image: 'wifi.png', size: 32, image: 'ipad-mini2.jpg', price_cents: 7500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad-mini2.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini 2', network: 'WIFI ONLY', network_image: 'wifi.png', size: 128, image: 'ipad-mini2.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-mini.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-mini.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-mini.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-mini.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-mini.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-mini.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-mini.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-mini.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-mini.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-mini.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-mini.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-mini.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad-mini.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'ipad-mini.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad-mini.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad-mini.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'WIFI ONLY', network_image: 'wifi.png', size: 32, image: 'ipad-mini.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'mini', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad-mini.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 9500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 9500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 9500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 9500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 9000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 9500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 10000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 11000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad-4gen.jpg', price_cents: 8000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 32, image: 'ipad-4gen.jpg', price_cents: 8500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad-4gen.jpg', price_cents: 9500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '4th generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 128, image: 'ipad-4gen.jpg', price_cents: 10500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 6500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 7000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 6500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 7000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 6500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 7000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 6500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 7000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 6500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 7000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad-3gen.jpg', price_cents: 5500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 32, image: 'ipad-3gen.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '3rd generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad-3gen.jpg', price_cents: 6500, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad-2gen.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 32, image: 'ipad-2gen.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: '2nd generation', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad-2gen.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'WIFI ONLY', network_image: 'wifi.png', size: 16, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'WIFI ONLY', network_image: 'wifi.png', size: 32, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPad', device_model: 'original', network: 'WIFI ONLY', network_image: 'wifi.png', size: 64, image: 'ipad.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 26500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 27500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 28500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 23500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 25000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 26000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 23000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 24500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 26000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 26500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 27500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 28500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 23500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 25000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 26000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'iphone-6splus.jpg', price_cents: 26500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'iphone-6splus.jpg', price_cents: 27500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s Plus', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'iphone-6splus.jpg', price_cents: 28500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 22500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 25000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 26500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 22500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 25000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 22500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 25500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 22500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 25000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 26000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone-6s.jpg', price_cents: 22500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone-6s.jpg', price_cents: 24000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'iphone-6s.jpg', price_cents: 25000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'iphone-6s.jpg', price_cents: 22500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'iphone-6s.jpg', price_cents: 25000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6s', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'iphone-6s.jpg', price_cents: 26500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 18500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 17000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 18000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 17000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 18500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone6plus.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone6plus.jpg', price_cents: 17000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'iphone6plus.jpg', price_cents: 18000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'iphone6plus.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'iphone6plus.jpg', price_cents: 18500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6 Plus', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'iphone6plus.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 16500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'ATT', network_image: 'att-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 14000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Sprint', network_image: 'sprint-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 12000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 13000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 14000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 16500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Verizon', network_image: 'verizon-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone6.jpg', price_cents: 14000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone6.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Other', network_image: 'wireless-tower-svg.png', size: 128, image: 'iphone6.jpg', price_cents: 16000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'iphone6.jpg', price_cents: 15000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'iphone6.jpg', price_cents: 16500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '6', network: 'Unlocked', network_image: 'unlocked.png', size: 128, image: 'iphone6.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 22500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 22500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone-se.jpg', price_cents: 17500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'iphone-se.jpg', price_cents: 20000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: 'SE', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'iphone-se.jpg', price_cents: 22500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 7500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 8000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 8500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 5500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 6500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 6500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 7500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 8500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 9500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone5s.jpg', price_cents: 5500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'iphone5s.jpg', price_cents: 6000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone5s.jpg', price_cents: 6500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'iphone5s.jpg', price_cents: 7500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'iphone5s.jpg', price_cents: 8000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5s', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'iphone5s.jpg', price_cents: 8500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'ATT', network_image: 'att-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 3500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 3000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Sprint', network_image: 'sprint-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 2500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 3500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 2500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 2500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 3000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 3500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Verizon', network_image: 'verizon-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 3000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone5c.jpg', price_cents: 3000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Other', network_image: 'wireless-tower-svg.png', size: 8, image: 'iphone5c.jpg', price_cents: 2500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'iphone5c.jpg', price_cents: 3500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'iphone5c.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Unlocked', network_image: 'unlocked.png', size: 8, image: 'iphone5c.jpg', price_cents: 3500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5c', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'iphone5c.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'ATT', network_image: 'att-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'ATT', network_image: 'att-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 5500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Sprint', network_image: 'sprint-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Sprint', network_image: 'sprint-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 2500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Verizon', network_image: 'verizon-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 4000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 4500, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Verizon', network_image: 'verizon-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 16, image: 'iphone5.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'iphone5.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 64, image: 'iphone5.jpg', price_cents: 2000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Unlocked', network_image: 'unlocked.png', size: 16, image: 'iphone5.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'iphone5.jpg', price_cents: 5000, brand_id: 1)
Device.create(device_type: 'iPhone', device_model: '5', network: 'Unlocked', network_image: 'unlocked.png', size: 64, image: 'iphone5.jpg', price_cents: 5500, brand_id: 1)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 18000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 18000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s7.png', price_cents: 18000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-s7.png', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 22500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 22500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S7 edge', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-s7edge.jpg', price_cents: 22500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 12500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 11000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 11000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 12500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s6.png', price_cents: 11000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-s6.png', price_cents: 12500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 12500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 12500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 12500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-6sedge.jpg', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge plus', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-6sedgeplus.png', price_cents: 17500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge plus', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-6sedgeplus.png', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge plus', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-6sedgeplus.png', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge plus', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-6sedgeplus.png', price_cents: 17500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge plus', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-6sedgeplus.png', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S6 edge plus', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-6sedgeplus.png', price_cents: 17500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 7500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 6000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 6000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 7500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 6000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S5', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-s5.jpg', price_cents: 7500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 5000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 3000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 3000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 5000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 3000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'S4', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-s4.jpg', price_cents: 5000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 5', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-note5.jpg', price_cents: 20000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note edge', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-note-edge.jpg', price_cents: 15000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 10000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 10000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 10000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 10000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 10000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 4', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-note4.jpg', price_cents: 10000, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'ATT', network_image: 'att-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 6500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'Sprint', network_image: 'sprint-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 6500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'T-Mobile', network_image: 'tmobile-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 6500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'Verizon', network_image: 'verizon-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 6500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'Other', network_image: 'wireless-tower-svg.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 6500, brand_id: 2)
Device.create(device_type: 'Galaxy', device_model: 'Note 3', network: 'Unlocked', network_image: 'unlocked.png', size: 32, image: 'galaxy-note3.jpg', price_cents: 6500, brand_id: 2)

AdminUser.create!(email: 'ethansteiner@gmail.com', text_mail: '3478731681@vtext.com', password: 'password', password_confirmation: 'password')
AdminUser.create!(email: 'ds@buybackcorps.com', text_mail: '9179681335@vtext.com', password: 'buybackers', password_confirmation: 'buybackers')

Quote.create(name: "Ethan Steiner", phone: '3478731681', device: 'iPhone', model: '6', network: 'ATT', size: 16, price: 100, condition: 'normal')
